'use strict';

const logger = require('./logger');
// ⚠️ SCHEMA FREEZE — do NOT add new DDL here.
// All DDL in this file has been consolidated into
// api/migrations/007_consolidated_runtime_schema.sql (generated by
// tools/extract-runtime-ddl.cjs). This file keeps running at boot for
// backwards compatibility on existing servers, but every NEW schema
// change must be a numbered file in api/migrations/.
const { VALID_BRANCHES } = require('../constants/permissions');
const { branchIdForBranch } = require('./branches');

function registerStartupTasks({ pool, tryJson, VALID_PAY_TYPES, VALID_SOURCES, sendWhatsApp, uuidv4 }) {
  // ── Schema migrations (run once per version, not on every boot) ──────────────
  const SCHEMA_V = 42;
  // Migration catch helper — silences expected errors (duplicate column/index/table)
  // but logs anything unexpected so bugs don't hide silently.
  const migCatch = (e) => {
    const msg = e.message || '';
    if (msg.includes('Duplicate') || msg.includes('already exists') || (e.code && e.code.startsWith('ER_DUP'))) return;
    logger.warn('[migration]', e.code || '', msg.slice(0, 200));
  };
  const columnExists = async (tableName, columnName) => {
    const [rows] = await pool.query(
      `SELECT 1 FROM information_schema.columns
       WHERE table_schema = DATABASE() AND table_name = ? AND column_name = ?
       LIMIT 1`,
      [tableName, columnName]
    );
    return rows.length > 0;
  };
  const addIndexIfColumnsExist = async (tableName, indexName, columnsSql, requiredColumns) => {
    try {
      const checks = await Promise.all(requiredColumns.map((columnName) => columnExists(tableName, columnName)));
      if (!checks.every(Boolean)) {
        logger.warn(`[migration] skipped ${indexName}: missing column on ${tableName}`);
        return;
      }
      await pool.query(`ALTER TABLE ${tableName} ADD INDEX IF NOT EXISTS ${indexName} (${columnsSql})`);
    } catch (e) {
      migCatch(e);
    }
  };
  (async () => {
    try {
      // site_config may not exist on first boot — create it first
      await pool.query(`CREATE TABLE IF NOT EXISTS site_config (
        \`key\` VARCHAR(100) PRIMARY KEY,
        \`value\` LONGTEXT,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
      let currentV = 0;
      try {
        const [[cfgRow]] = await pool.query("SELECT `value` FROM site_config WHERE `key` = 'schema_version' LIMIT 1");
        currentV = parseInt(cfgRow?.value || '0', 10);
      } catch (_) { /* site_config not ready yet — will run next boot */ }
      if (currentV < SCHEMA_V) {
        // v1 migrations
        await pool.query('ALTER TABLE leads ADD COLUMN IF NOT EXISTS score INT NOT NULL DEFAULT 0').catch(migCatch);
        await pool.query('ALTER TABLE leads ADD COLUMN IF NOT EXISTS deal_value DECIMAL(10,2) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT NULL').catch(migCatch);
        await pool.query(`ALTER TABLE orders MODIFY COLUMN payment_method VARCHAR(50) NOT NULL DEFAULT 'CARD'`).catch(migCatch);
        await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS staff_id VARCHAR(36) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS staff_name VARCHAR(255) DEFAULT NULL').catch(migCatch);
        await pool.query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS status ENUM('pending','paid','failed') NOT NULL DEFAULT 'paid'").catch(migCatch);
        // Community customer-posting + moderation: posts default to 'approved' so existing/admin
        // rows stay visible; customer-submitted posts are inserted as 'pending' for review.
        await pool.query("ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'approved'").catch(migCatch);
        await pool.query('ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS author_role VARCHAR(80) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS subscriber_id VARCHAR(64) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE payment_proofs CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci').catch(migCatch);
        await pool.query('ALTER TABLE payments ADD INDEX idx_payments_course_id (course_id)').catch(migCatch);
        await pool.query('ALTER TABLE payments ADD UNIQUE INDEX idx_payments_txn (transaction_id)').catch(migCatch);
        await pool.query('ALTER TABLE leads ADD INDEX idx_leads_score (score)').catch(migCatch);
        // v2 migrations — ensure subscribers has sales/branch columns + backfill from crm_json
        await pool.query('ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS assigned_sales_id VARCHAR(36) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS assigned_sales_name VARCHAR(255) DEFAULT NULL').catch(migCatch);
        await pool.query("ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS branch ENUM('DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','OTHER') DEFAULT NULL").catch(migCatch);
        // Backfill assigned_sales_id + assigned_sales_name + branch from crm_json for existing subscribers
        try {
          const [rows] = await pool.query(
            "SELECT id, crm_json FROM subscribers WHERE (assigned_sales_id IS NULL OR branch IS NULL) AND crm_json IS NOT NULL LIMIT 5000"
          );
          let backfilled = 0;
          for (const row of rows) {
            try {
              const crm = JSON.parse(row.crm_json || '{}');
              const salesId   = crm.assignedSalesId   || null;
              const salesName = crm.assignedSalesName || null;
              const rawBranch = crm.branch || null;
              const normBranch = rawBranch ? rawBranch.toUpperCase().replace(/[-\s]/g,'_') : null;
              const branchVal = (normBranch && VALID_BRANCHES.has(normBranch)) ? normBranch : null;
              if (salesId || branchVal) {
                await pool.query(
                  'UPDATE subscribers SET assigned_sales_id=COALESCE(assigned_sales_id,?), assigned_sales_name=COALESCE(assigned_sales_name,?), branch=COALESCE(branch,?) WHERE id=?',
                  [salesId, salesName, branchVal, row.id]
                );
                backfilled++;
              }
            } catch (_) {}
          }
          logger.info(`[schema] v2: backfilled ${backfilled} subscribers with sales/branch data`);
        } catch (bf) { logger.warn('[schema] backfill error (non-fatal):', bf.message); }
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', ?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)",
          [String(SCHEMA_V)]
        ).catch(migCatch);
        logger.info(`[schema] Migrations v${SCHEMA_V} applied`);
      }
      // ── v3: Normalize branch values in DB (lowercase → ENUM uppercase) ─────────
      // Runs every boot — cheap UPDATE WHERE only touches rows that need fixing.
      if (currentV < 3) {
        const branchMap = {
          'online-egypt': 'ONLINE_EGYPT', 'online egypt': 'ONLINE_EGYPT', 'online_egypt': 'ONLINE_EGYPT',
          'online-saudi': 'ONLINE_SAUDI', 'online saudi': 'ONLINE_SAUDI', 'online_saudi': 'ONLINE_SAUDI',
          'online-abroad': 'ONLINE_ABROAD', 'online abroad': 'ONLINE_ABROAD', 'online_abroad': 'ONLINE_ABROAD',
          'daqqi': 'DAQQI', 'tagamoa': 'TAGAMOA', 'other': 'OTHER',
          'اون لاين': 'ONLINE_EGYPT', 'online': 'ONLINE_EGYPT',
        };
        // Fix subscribers branch column
        for (const [bad, good] of Object.entries(branchMap)) {
          await pool.query(
            "UPDATE subscribers SET branch=? WHERE LOWER(branch)=? AND branch != ?",
            [good, bad, good]
          ).catch(migCatch);
        }
        // Fix leads branch column (stored as VARCHAR)
        for (const [bad, good] of Object.entries(branchMap)) {
          await pool.query(
            "UPDATE leads SET branch=? WHERE LOWER(branch)=? AND branch != ?",
            [good, bad, good]
          ).catch(migCatch);
        }
        // Also normalize crm_json.branch inside subscribers JSON
        try {
          const [rows] = await pool.query(
            `SELECT id, crm_json FROM subscribers WHERE crm_json LIKE '%online-egypt%' OR crm_json LIKE '%online-saudi%' OR crm_json LIKE '%online-abroad%' LIMIT 3000`
          );
          for (const row of rows) {
            try {
              const crm = tryJson(row.crm_json, {});
              if (crm.branch) {
                const normB = crm.branch.toUpperCase().replace(/[-\s]/g, '_');
                const VALID = new Set(['DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','OTHER']);
                if (VALID.has(normB) && crm.branch !== normB) {
                  crm.branch = normB;
                  await pool.query('UPDATE subscribers SET crm_json=? WHERE id=?', [JSON.stringify(crm), row.id]).catch(migCatch);
                }
              }
            } catch (_) {}
          }
        } catch (_) {}
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '3') ON DUPLICATE KEY UPDATE `value`='3'"
        ).catch(migCatch);
        logger.info('[schema] v3: branch normalization complete');
      }
      // ── v4: Ensure assigned_cs_id column + index on subscribers ───────────────
      if (currentV < 4) {
        await pool.query('ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS assigned_cs_id VARCHAR(36) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS assigned_cs_name VARCHAR(255) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE subscribers ADD INDEX IF NOT EXISTS idx_subs_cs_id (assigned_cs_id)').catch(migCatch);
        // Backfill assigned_cs_id from crm_json.assignedCollectionId for existing records
        try {
          const [rows] = await pool.query(
            "SELECT id, crm_json FROM subscribers WHERE assigned_cs_id IS NULL AND crm_json IS NOT NULL LIMIT 5000"
          );
          let filled = 0;
          for (const row of rows) {
            try {
              const crm = tryJson(row.crm_json, {});
              const csId   = crm.assignedCollectionId   || null;
              const csName = crm.assignedCollectionName || null;
              if (csId) {
                await pool.query('UPDATE subscribers SET assigned_cs_id=?, assigned_cs_name=? WHERE id=?', [csId, csName, row.id]).catch(migCatch);
                filled++;
              }
            } catch (_) {}
          }
          if (filled) logger.info(`[schema] v4: backfilled ${filled} subscribers with assigned_cs_id`);
        } catch (_) {}
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '4') ON DUPLICATE KEY UPDATE `value`='4'"
        ).catch(migCatch);
        logger.info('[schema] v4: assigned_cs_id column + index ready');
      }
      // ── v5: payment_audit_log table ───────────────────────────────────────────
      if (currentV < 5) {
        await pool.query(`
          CREATE TABLE IF NOT EXISTS payment_audit_log (
            id VARCHAR(36) PRIMARY KEY,
            payment_id VARCHAR(36) NOT NULL,
            action ENUM('create','update','delete') NOT NULL,
            old_status VARCHAR(50) DEFAULT NULL,
            new_status VARCHAR(50) DEFAULT NULL,
            amount DECIMAL(10,2) DEFAULT NULL,
            subscriber_id VARCHAR(36) DEFAULT NULL,
            actor VARCHAR(255) DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_audit_payment (payment_id),
            INDEX idx_audit_subscriber (subscriber_id),
            INDEX idx_audit_created (created_at)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '5') ON DUPLICATE KEY UPDATE `value`='5'"
        ).catch(migCatch);
        logger.info('[schema] v5: payment_audit_log table created');
      }
      // ── v6: OTP codes + promo_codes + notifications ───────────────────────────
      if (currentV < 6) {
        // OTP codes (password reset + admin 2FA)
        await pool.query(`
          CREATE TABLE IF NOT EXISTS otp_codes (
            id VARCHAR(36) PRIMARY KEY,
            user_id VARCHAR(36) NOT NULL,
            email VARCHAR(255) NOT NULL,
            code VARCHAR(10) NOT NULL,
            type ENUM('password_reset','2fa') NOT NULL DEFAULT 'password_reset',
            expires_at DATETIME NOT NULL,
            used TINYINT(1) NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_otp_user (user_id),
            INDEX idx_otp_email (email),
            INDEX idx_otp_expires (expires_at)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // Promo/discount codes
        await pool.query(`
          CREATE TABLE IF NOT EXISTS promo_codes (
            id VARCHAR(36) PRIMARY KEY,
            code VARCHAR(50) NOT NULL UNIQUE,
            description VARCHAR(255) DEFAULT NULL,
            discount_type ENUM('percent','fixed') NOT NULL DEFAULT 'percent',
            discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
            min_order_amount DECIMAL(10,2) DEFAULT 0,
            max_uses INT DEFAULT NULL,
            used_count INT NOT NULL DEFAULT 0,
            expires_at DATETIME DEFAULT NULL,
            active TINYINT(1) NOT NULL DEFAULT 1,
            created_by VARCHAR(255) DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_promo_code (code),
            INDEX idx_promo_active (active)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // Admin notifications
        await pool.query(`
          CREATE TABLE IF NOT EXISTS notifications (
            id VARCHAR(36) PRIMARY KEY,
            type VARCHAR(50) NOT NULL DEFAULT 'info',
            title VARCHAR(255) NOT NULL,
            message TEXT DEFAULT NULL,
            data_json TEXT DEFAULT NULL,
            read_at DATETIME DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_notif_created (created_at),
            INDEX idx_notif_read (read_at)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '6') ON DUPLICATE KEY UPDATE `value`='6'"
        ).catch(migCatch);
        logger.info('[schema] v6: otp_codes + promo_codes + notifications tables created');
      }
      // ── v7: course_ratings table ──────────────────────────────────────────────
      if (currentV < 7) {
        await pool.query(`
          CREATE TABLE IF NOT EXISTS course_ratings (
            id VARCHAR(36) PRIMARY KEY,
            course_id VARCHAR(36) NOT NULL,
            subscriber_id VARCHAR(36) NOT NULL,
            rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
            comment TEXT DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uq_rating (course_id, subscriber_id),
            INDEX idx_cr_course (course_id),
            INDEX idx_cr_subscriber (subscriber_id)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '7') ON DUPLICATE KEY UPDATE `value`='7'"
        ).catch(migCatch);
        logger.info('[schema] v7: course_ratings table created');
      }
      // ── v8: course_completions + referral_codes + view_count on lectures ──────
      if (currentV < 8) {
        // Digital course completion certificates (auto-generated, lightweight)
        await pool.query(`
          CREATE TABLE IF NOT EXISTS course_completions (
            id VARCHAR(36) PRIMARY KEY,
            subscriber_id VARCHAR(36) NOT NULL,
            course_id VARCHAR(36) NOT NULL,
            completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            certificate_code VARCHAR(20) NOT NULL UNIQUE,
            email_sent TINYINT(1) NOT NULL DEFAULT 0,
            UNIQUE KEY uq_completion (subscriber_id, course_id),
            INDEX idx_comp_course (course_id),
            INDEX idx_comp_subscriber (subscriber_id)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        // Referral codes
        await pool.query(`
          CREATE TABLE IF NOT EXISTS referral_codes (
            id VARCHAR(36) PRIMARY KEY,
            subscriber_id VARCHAR(36) NOT NULL UNIQUE,
            code VARCHAR(20) NOT NULL UNIQUE,
            uses INT NOT NULL DEFAULT 0,
            earnings DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_ref_code (code)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        // Fix type mismatch if tables were already created with INT subscriber_id
        await pool.query('ALTER TABLE course_completions MODIFY COLUMN subscriber_id VARCHAR(36) NOT NULL').catch(migCatch);
        await pool.query('ALTER TABLE referral_codes MODIFY COLUMN subscriber_id VARCHAR(36) NOT NULL').catch(migCatch);
        // Track which subscriber was referred by whom
        await pool.query('ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS referred_by VARCHAR(20) DEFAULT NULL').catch(migCatch);
        // Per-lecture view counts for content analytics
        await pool.query('ALTER TABLE course_lectures ADD COLUMN IF NOT EXISTS view_count INT NOT NULL DEFAULT 0').catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '8') ON DUPLICATE KEY UPDATE `value`='8'"
        ).catch(migCatch);
        logger.info('[schema] v8: course_completions + referral_codes + view_count ready');
      }
      // ── v9: staff_name column on payments table ───────────────────────────────
      if (currentV < 9) {
        await pool.query('ALTER TABLE payments ADD COLUMN IF NOT EXISTS staff_name VARCHAR(255) DEFAULT NULL').catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '9') ON DUPLICATE KEY UPDATE `value`='9'"
        ).catch(migCatch);
        logger.info('[schema] v9: staff_name column on payments table ready');
      }
      // ── v10: from_account, source, item_title, cert_type columns on payments ──
      if (currentV < 10) {
        await pool.query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS from_account VARCHAR(255) DEFAULT NULL").catch(migCatch);
        await pool.query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS source ENUM('web','staff','reception','daqqi','paymob','system') DEFAULT NULL").catch(migCatch);
        await pool.query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS item_title VARCHAR(500) DEFAULT NULL").catch(migCatch);
        await pool.query("ALTER TABLE payments ADD COLUMN IF NOT EXISTS cert_type VARCHAR(255) DEFAULT NULL").catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '10') ON DUPLICATE KEY UPDATE `value`='10'"
        ).catch(migCatch);
        logger.info('[schema] v10: from_account, source, item_title, cert_type columns on payments ready');
      }
      // ── v11: token_blacklist table (persists revoked JWTs across restarts) ────
      if (currentV < 11) {
        await pool.query(`
          CREATE TABLE IF NOT EXISTS token_blacklist (
            jti VARCHAR(36) PRIMARY KEY,
            expires_at DATETIME NOT NULL,
            revoked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_tbl_expires (expires_at)
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '11') ON DUPLICATE KEY UPDATE `value`='11'"
        ).catch(migCatch);
        logger.info('[schema] v11: token_blacklist table ready');
      }
      // ── v12: lecture_progress table, email_campaigns, tasks, support_tickets, webhooks, budgets, nps ──
      if (currentV < 12) {
        // lecture_progress — per-subscriber per-lecture tracking (used by automation + admin)
        await pool.query(`CREATE TABLE IF NOT EXISTS lecture_progress (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          subscriber_id VARCHAR(36) NOT NULL,
          lecture_id VARCHAR(36) NOT NULL,
          course_id VARCHAR(36) DEFAULT NULL,
          progress_pct TINYINT UNSIGNED NOT NULL DEFAULT 0,
          completed_at DATETIME DEFAULT NULL,
          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          UNIQUE KEY uq_lp (subscriber_id, lecture_id),
          KEY idx_lp_sub (subscriber_id),
          KEY idx_lp_course (course_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // email_campaigns
        await pool.query(`CREATE TABLE IF NOT EXISTS email_campaigns (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          title VARCHAR(500) NOT NULL,
          subject VARCHAR(500) NOT NULL,
          body_html TEXT NOT NULL,
          audience ENUM('all','subscribers','leads','manual') NOT NULL DEFAULT 'all',
          audience_filter JSON DEFAULT NULL,
          status ENUM('draft','sending','sent','failed') NOT NULL DEFAULT 'draft',
          sent_count INT NOT NULL DEFAULT 0,
          fail_count INT NOT NULL DEFAULT 0,
          scheduled_at DATETIME DEFAULT NULL,
          sent_at DATETIME DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          created_by VARCHAR(36) DEFAULT NULL,
          PRIMARY KEY (id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // tasks
        await pool.query(`CREATE TABLE IF NOT EXISTS tasks (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          title VARCHAR(500) NOT NULL,
          description TEXT DEFAULT NULL,
          assigned_to VARCHAR(36) DEFAULT NULL,
          assigned_name VARCHAR(255) DEFAULT NULL,
          related_sub_id VARCHAR(36) DEFAULT NULL,
          related_lead_id VARCHAR(36) DEFAULT NULL,
          priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
          status ENUM('todo','in_progress','done','cancelled') NOT NULL DEFAULT 'todo',
          due_date DATE DEFAULT NULL,
          completed_at DATETIME DEFAULT NULL,
          created_by VARCHAR(36) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_tasks_assigned (assigned_to),
          KEY idx_tasks_status (status)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // support_tickets
        await pool.query(`CREATE TABLE IF NOT EXISTS support_tickets (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          subscriber_id VARCHAR(36) DEFAULT NULL,
          subscriber_email VARCHAR(255) DEFAULT NULL,
          subscriber_name VARCHAR(255) DEFAULT NULL,
          subject VARCHAR(500) NOT NULL,
          body TEXT NOT NULL,
          status ENUM('open','in_progress','resolved','closed') NOT NULL DEFAULT 'open',
          priority ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
          assigned_to VARCHAR(36) DEFAULT NULL,
          resolved_at DATETIME DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_tickets_sub (subscriber_id),
          KEY idx_tickets_status (status)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS ticket_replies (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          ticket_id VARCHAR(36) NOT NULL,
          author_type ENUM('subscriber','staff','system') NOT NULL DEFAULT 'staff',
          author_name VARCHAR(255) DEFAULT NULL,
          body TEXT NOT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_tr_ticket (ticket_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // webhooks
        await pool.query(`CREATE TABLE IF NOT EXISTS webhooks (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          name VARCHAR(255) NOT NULL,
          url VARCHAR(1000) NOT NULL,
          secret VARCHAR(255) DEFAULT NULL,
          events JSON NOT NULL DEFAULT ('[]'),
          is_active TINYINT(1) NOT NULL DEFAULT 1,
          last_triggered_at DATETIME DEFAULT NULL,
          last_status INT DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // budgets
        await pool.query(`CREATE TABLE IF NOT EXISTS budgets (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          month CHAR(7) NOT NULL COMMENT 'YYYY-MM',
          category VARCHAR(255) NOT NULL,
          budgeted_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
          currency CHAR(3) NOT NULL DEFAULT 'EGP',
          notes VARCHAR(500) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          UNIQUE KEY uq_budget (month, category)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // nps_responses
        await pool.query(`CREATE TABLE IF NOT EXISTS nps_responses (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          subscriber_id VARCHAR(36) DEFAULT NULL,
          subscriber_email VARCHAR(255) DEFAULT NULL,
          score TINYINT UNSIGNED NOT NULL COMMENT '0-10',
          comment TEXT DEFAULT NULL,
          payment_id VARCHAR(36) DEFAULT NULL,
          sent_at DATETIME DEFAULT NULL,
          responded_at DATETIME DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_nps_sub (subscriber_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // sms_campaigns
        await pool.query(`CREATE TABLE IF NOT EXISTS sms_campaigns (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          title VARCHAR(500) NOT NULL,
          message TEXT NOT NULL,
          audience ENUM('all','subscribers','leads','manual') NOT NULL DEFAULT 'all',
          audience_filter JSON DEFAULT NULL,
          status ENUM('draft','sending','sent','failed') NOT NULL DEFAULT 'draft',
          sent_count INT NOT NULL DEFAULT 0,
          fail_count INT NOT NULL DEFAULT 0,
          sent_at DATETIME DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          created_by VARCHAR(36) DEFAULT NULL,
          PRIMARY KEY (id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '12') ON DUPLICATE KEY UPDATE `value`='12'"
        ).catch(migCatch);
        logger.info('[schema] v12: lecture_progress, email_campaigns, tasks, support_tickets, webhooks, budgets, nps, sms_campaigns ready');
      }

      // ── v13: HR System — departments, attendance, leaves, salary, commissions, KPI ──
      if (currentV < 13) {
        await pool.query(`CREATE TABLE IF NOT EXISTS hr_departments (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          name VARCHAR(255) NOT NULL,
          branch ENUM('DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','ALL') NOT NULL DEFAULT 'ALL',
          manager_id VARCHAR(36) DEFAULT NULL,
          description TEXT DEFAULT NULL,
          is_active TINYINT(1) NOT NULL DEFAULT 1,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_dept_branch (branch)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // Extend staff table with HR fields
        await pool.query('ALTER TABLE staff ADD COLUMN IF NOT EXISTS department_id VARCHAR(36) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE staff ADD COLUMN IF NOT EXISTS manager_id VARCHAR(36) DEFAULT NULL').catch(migCatch);
        await pool.query("ALTER TABLE staff ADD COLUMN IF NOT EXISTS employment_type ENUM('FULL_TIME','PART_TIME','CONTRACT','FREELANCE') NOT NULL DEFAULT 'FULL_TIME'").catch(migCatch);
        await pool.query('ALTER TABLE staff ADD COLUMN IF NOT EXISTS hire_date DATE DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE staff ADD COLUMN IF NOT EXISTS birth_date DATE DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE staff ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255) DEFAULT NULL').catch(migCatch);
        await pool.query('ALTER TABLE staff ADD COLUMN IF NOT EXISTS termination_date DATE DEFAULT NULL').catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS salary_structures (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          base_salary DECIMAL(10,2) NOT NULL DEFAULT 0,
          housing_allowance DECIMAL(10,2) NOT NULL DEFAULT 0,
          transport_allowance DECIMAL(10,2) NOT NULL DEFAULT 0,
          other_allowances_json JSON DEFAULT NULL,
          currency ENUM('EGP','SAR','USD') NOT NULL DEFAULT 'EGP',
          effective_from DATE NOT NULL,
          effective_to DATE DEFAULT NULL,
          created_by VARCHAR(36) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_salary_staff (staff_id),
          KEY idx_salary_effective (staff_id, effective_from)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS commission_rules (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          name VARCHAR(255) NOT NULL,
          staff_id VARCHAR(36) DEFAULT NULL,
          apply_to_roles JSON DEFAULT NULL,
          calc_type ENUM('PERCENTAGE','FIXED_PER_SALE','TIERED','TARGET_BONUS') NOT NULL DEFAULT 'PERCENTAGE',
          percentage_value DECIMAL(5,2) DEFAULT NULL,
          tiers_json JSON DEFAULT NULL,
          target_amount DECIMAL(10,2) DEFAULT NULL,
          bonus_value DECIMAL(10,2) DEFAULT NULL,
          bonus_type ENUM('FIXED','PERCENTAGE') DEFAULT NULL,
          applies_to ENUM('PAYMENT','COURSE_ONLY','CONSULTATION_ONLY','ENROLLMENT') NOT NULL DEFAULT 'PAYMENT',
          min_payment DECIMAL(10,2) DEFAULT NULL,
          currency ENUM('EGP','SAR','USD') NOT NULL DEFAULT 'EGP',
          priority INT NOT NULL DEFAULT 1,
          stackable TINYINT(1) NOT NULL DEFAULT 0,
          effective_from DATE NOT NULL DEFAULT (CURRENT_DATE),
          effective_to DATE DEFAULT NULL,
          is_active TINYINT(1) NOT NULL DEFAULT 1,
          created_by VARCHAR(36) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_crules_staff (staff_id),
          KEY idx_crules_active (is_active)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS crm_commissions (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          payment_id VARCHAR(36) DEFAULT NULL,
          rule_id VARCHAR(36) DEFAULT NULL,
          client_id VARCHAR(36) DEFAULT NULL,
          client_type ENUM('SUBSCRIBER','LEAD') DEFAULT 'SUBSCRIBER',
          payment_amount DECIMAL(10,2) NOT NULL,
          commission_amount DECIMAL(10,2) NOT NULL,
          calc_details JSON DEFAULT NULL,
          month TINYINT UNSIGNED NOT NULL,
          year SMALLINT UNSIGNED NOT NULL,
          status ENUM('PENDING','INCLUDED_IN_PAYROLL','PAID','CANCELLED') NOT NULL DEFAULT 'PENDING',
          payroll_run_id VARCHAR(36) DEFAULT NULL,
          note TEXT DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_comm_staff (staff_id),
          KEY idx_comm_month (staff_id, year, month),
          KEY idx_comm_payment (payment_id),
          KEY idx_comm_status (status),
          UNIQUE KEY uniq_comm_payment_staff (payment_id, staff_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS kpi_targets (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          metric VARCHAR(100) NOT NULL,
          target_value DECIMAL(12,2) NOT NULL,
          period ENUM('MONTHLY','QUARTERLY','YEARLY') NOT NULL DEFAULT 'MONTHLY',
          from_date DATE NOT NULL,
          to_date DATE NOT NULL,
          notes TEXT DEFAULT NULL,
          set_by VARCHAR(36) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_kpit_staff (staff_id),
          KEY idx_kpit_period (staff_id, metric, from_date)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS kpi_actuals (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          metric VARCHAR(100) NOT NULL,
          actual_value DECIMAL(12,2) NOT NULL DEFAULT 0,
          period ENUM('MONTHLY','QUARTERLY','YEARLY') NOT NULL DEFAULT 'MONTHLY',
          period_start DATE NOT NULL,
          period_end DATE NOT NULL,
          source ENUM('CRM_AUTO','ATTENDANCE_AUTO','MANUAL') NOT NULL DEFAULT 'CRM_AUTO',
          breakdown_json JSON DEFAULT NULL,
          calculated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          UNIQUE KEY uniq_kpi_actual (staff_id, metric, period, period_start),
          KEY idx_kpia_staff (staff_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS payroll_runs (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          month TINYINT UNSIGNED NOT NULL,
          year SMALLINT UNSIGNED NOT NULL,
          status ENUM('DRAFT','CALCULATED','APPROVED','PAID','CANCELLED') NOT NULL DEFAULT 'DRAFT',
          total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
          employee_count INT NOT NULL DEFAULT 0,
          currency ENUM('EGP','SAR','USD') NOT NULL DEFAULT 'EGP',
          notes TEXT DEFAULT NULL,
          calculated_by VARCHAR(36) DEFAULT NULL,
          approved_by VARCHAR(36) DEFAULT NULL,
          paid_by VARCHAR(36) DEFAULT NULL,
          calculated_at DATETIME DEFAULT NULL,
          approved_at DATETIME DEFAULT NULL,
          paid_at DATETIME DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          UNIQUE KEY uniq_payroll_run (month, year),
          KEY idx_pr_status (status)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS payroll_items (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          payroll_run_id VARCHAR(36) NOT NULL,
          staff_id VARCHAR(36) NOT NULL,
          base_salary DECIMAL(10,2) NOT NULL DEFAULT 0,
          allowances_json JSON DEFAULT NULL,
          total_allowances DECIMAL(10,2) NOT NULL DEFAULT 0,
          commission DECIMAL(10,2) NOT NULL DEFAULT 0,
          bonus DECIMAL(10,2) NOT NULL DEFAULT 0,
          bonus_note TEXT DEFAULT NULL,
          late_deductions DECIMAL(10,2) NOT NULL DEFAULT 0,
          absence_deductions DECIMAL(10,2) NOT NULL DEFAULT 0,
          advance_deductions DECIMAL(10,2) NOT NULL DEFAULT 0,
          other_deductions DECIMAL(10,2) NOT NULL DEFAULT 0,
          deductions_note TEXT DEFAULT NULL,
          net_salary DECIMAL(10,2) NOT NULL DEFAULT 0,
          attendance_days INT DEFAULT NULL,
          absent_days INT DEFAULT NULL,
          late_minutes INT DEFAULT NULL,
          commission_count INT DEFAULT NULL,
          calculation_details JSON DEFAULT NULL,
          is_manual_override TINYINT(1) NOT NULL DEFAULT 0,
          override_by VARCHAR(36) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          UNIQUE KEY uniq_payroll_item (payroll_run_id, staff_id),
          KEY idx_pi_staff (staff_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS work_schedules (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          day_of_week TINYINT NOT NULL COMMENT '0=Sun 6=Sat',
          start_time TIME NOT NULL DEFAULT '09:00:00',
          end_time TIME NOT NULL DEFAULT '17:00:00',
          grace_minutes INT NOT NULL DEFAULT 15,
          is_off_day TINYINT(1) NOT NULL DEFAULT 0,
          PRIMARY KEY (id),
          UNIQUE KEY uniq_schedule (staff_id, day_of_week)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS attendance_logs (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          branch ENUM('DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','OTHER') DEFAULT NULL,
          date DATE NOT NULL,
          check_in TIME DEFAULT NULL,
          check_out TIME DEFAULT NULL,
          total_hours DECIMAL(5,2) DEFAULT NULL,
          late_minutes INT NOT NULL DEFAULT 0,
          status ENUM('PRESENT','ABSENT','LATE','HALF_DAY','LEAVE','HOLIDAY','REMOTE') NOT NULL DEFAULT 'PRESENT',
          notes TEXT DEFAULT NULL,
          source ENUM('FINGERPRINT_IMPORT','MANUAL_ENTRY','APP') NOT NULL DEFAULT 'FINGERPRINT_IMPORT',
          import_batch_id VARCHAR(36) DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          UNIQUE KEY uniq_attendance (staff_id, date),
          KEY idx_att_staff (staff_id),
          KEY idx_att_date (date)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS attendance_import_batches (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          filename VARCHAR(255) NOT NULL,
          month TINYINT UNSIGNED NOT NULL,
          year SMALLINT UNSIGNED NOT NULL,
          branch ENUM('DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','OTHER') DEFAULT NULL,
          rows_total INT NOT NULL DEFAULT 0,
          rows_ok INT NOT NULL DEFAULT 0,
          rows_error INT NOT NULL DEFAULT 0,
          errors_json JSON DEFAULT NULL,
          imported_by VARCHAR(36) DEFAULT NULL,
          imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS leaves (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          type ENUM('ANNUAL','SICK','UNPAID','MATERNITY','EMERGENCY','PERMISSION','OTHER') NOT NULL DEFAULT 'ANNUAL',
          start_date DATE NOT NULL,
          end_date DATE NOT NULL,
          total_days DECIMAL(4,1) NOT NULL DEFAULT 1,
          reason TEXT DEFAULT NULL,
          status ENUM('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
          approved_by VARCHAR(36) DEFAULT NULL,
          approved_at DATETIME DEFAULT NULL,
          admin_note TEXT DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_leaves_staff (staff_id),
          KEY idx_leaves_dates (start_date, end_date),
          KEY idx_leaves_status (status)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS salary_advances (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          amount DECIMAL(10,2) NOT NULL,
          currency ENUM('EGP','SAR','USD') NOT NULL DEFAULT 'EGP',
          reason TEXT DEFAULT NULL,
          status ENUM('PENDING','APPROVED','DEDUCTED','REJECTED') NOT NULL DEFAULT 'PENDING',
          deduct_month TINYINT UNSIGNED DEFAULT NULL,
          deduct_year SMALLINT UNSIGNED DEFAULT NULL,
          approved_by VARCHAR(36) DEFAULT NULL,
          approved_at DATETIME DEFAULT NULL,
          created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY (id),
          KEY idx_advances_staff (staff_id)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        await pool.query(`CREATE TABLE IF NOT EXISTS hr_audit_logs (
          id VARCHAR(36) NOT NULL DEFAULT (UUID()),
          action VARCHAR(100) NOT NULL,
          entity_type VARCHAR(50) NOT NULL,
          entity_id VARCHAR(36) DEFAULT NULL,
          old_value JSON DEFAULT NULL,
          new_value JSON DEFAULT NULL,
          performed_by VARCHAR(36) DEFAULT NULL,
          performed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          ip_address VARCHAR(45) DEFAULT NULL,
          note TEXT DEFAULT NULL,
          PRIMARY KEY (id),
          KEY idx_hral_entity (entity_type, entity_id),
          KEY idx_hral_date (performed_at)
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);

        // Seed initial departments
        await pool.query(`INSERT IGNORE INTO hr_departments (id, name, branch, description) VALUES
          (UUID(),'المبيعات','ALL','فريق المبيعات وخدمة العملاء'),
          (UUID(),'التدريس','ALL','المدرسون والمحاضرون'),
          (UUID(),'الحسابات','ALL','الفريق المحاسبي والمالي'),
          (UUID(),'الإدارة','ALL','الإدارة العليا والـ HR')
        `).catch(migCatch);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '13') ON DUPLICATE KEY UPDATE `value`='13'"
        ).catch(migCatch);
        logger.info('[schema] v13: HR system tables ready (departments, attendance, leaves, salary, commissions, KPI)');
      }

      // ── v14: Recruitment + Onboarding tables ──────────────────────────────────
      if (currentV < 14) {
        await pool.query(`CREATE TABLE IF NOT EXISTS job_postings (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          title VARCHAR(200) NOT NULL,
          department_id VARCHAR(36),
          employment_type ENUM('full_time','part_time','contract','intern') DEFAULT 'full_time',
          description TEXT,
          requirements TEXT,
          salary_min DECIMAL(10,2),
          salary_max DECIMAL(10,2),
          status ENUM('draft','open','closed','filled') DEFAULT 'open',
          posted_by VARCHAR(36),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS job_applicants (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          job_id VARCHAR(36) NOT NULL,
          name VARCHAR(200) NOT NULL,
          email VARCHAR(200),
          phone VARCHAR(50),
          cv_url TEXT,
          notes TEXT,
          stage ENUM('applied','screening','interview','offer','hired','rejected') DEFAULT 'applied',
          stage_notes TEXT,
          updated_by VARCHAR(36),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS onboarding_templates (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          name VARCHAR(200) NOT NULL,
          role VARCHAR(100),
          description TEXT,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS onboarding_tasks (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          template_id VARCHAR(36) NOT NULL,
          title VARCHAR(300) NOT NULL,
          description TEXT,
          due_days INT DEFAULT 7,
          category ENUM('documents','training','setup','meeting','other') DEFAULT 'other',
          sort_order INT DEFAULT 0
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS employee_onboarding (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          template_id VARCHAR(36),
          started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          completed_at TIMESTAMP NULL,
          status ENUM('in_progress','completed','cancelled') DEFAULT 'in_progress'
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS employee_onboarding_items (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          onboarding_id VARCHAR(36) NOT NULL,
          task_title VARCHAR(300) NOT NULL,
          category VARCHAR(50) DEFAULT 'other',
          due_date DATE,
          completed_at TIMESTAMP NULL,
          completed_by VARCHAR(36),
          notes TEXT,
          sort_order INT DEFAULT 0
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '14') ON DUPLICATE KEY UPDATE `value`='14'"
        ).catch(migCatch);
        logger.info('[schema] v14: Recruitment + Onboarding tables ready');
      }

      // ── v15: Disciplinary records + document vault ──────────────────────────
      if (currentV < 15) {
        await pool.query(`CREATE TABLE IF NOT EXISTS disciplinary_records (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          type ENUM('warning','verbal_warning','written_warning','suspension','termination','other') DEFAULT 'warning',
          severity ENUM('low','medium','high') DEFAULT 'medium',
          title VARCHAR(300) NOT NULL,
          description TEXT,
          incident_date DATE,
          action_taken TEXT,
          issued_by VARCHAR(36),
          acknowledged_at DATETIME NULL,
          acknowledged_by VARCHAR(36) NULL,
          status ENUM('open','acknowledged','resolved','appealed') DEFAULT 'open',
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS employee_documents (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          title VARCHAR(300) NOT NULL,
          category ENUM('contract','id','certificate','medical','other') DEFAULT 'other',
          file_url TEXT,
          file_name VARCHAR(300),
          expiry_date DATE NULL,
          uploaded_by VARCHAR(36),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '15') ON DUPLICATE KEY UPDATE `value`='15'"
        ).catch(migCatch);
        logger.info('[schema] v15: Disciplinary + Documents tables ready');
      }

      // ── v16: Instructor rates + Employee bonuses ────────────────────────────
      if (currentV < 16) {
        await pool.query(`CREATE TABLE IF NOT EXISTS instructor_rates (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL UNIQUE,
          consultation_rate_type ENUM('per_session','percentage','per_hour') DEFAULT 'per_session',
          consultation_rate_value DECIMAL(10,2) DEFAULT 0,
          lecture_rate_per_hour DECIMAL(10,2) DEFAULT 0,
          training_rate_per_hour DECIMAL(10,2) DEFAULT 0,
          currency ENUM('EGP','SAR','USD') DEFAULT 'EGP',
          notes TEXT,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(`CREATE TABLE IF NOT EXISTS employee_bonuses (
          id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
          staff_id VARCHAR(36) NOT NULL,
          type ENUM('bonus','deduction') DEFAULT 'bonus',
          amount DECIMAL(10,2) NOT NULL,
          currency ENUM('EGP','SAR','USD') DEFAULT 'EGP',
          reason TEXT,
          for_month TINYINT UNSIGNED,
          for_year SMALLINT UNSIGNED,
          created_by VARCHAR(36),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          KEY idx_bonuses_staff (staff_id),
          KEY idx_bonuses_period (for_year, for_month)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '16') ON DUPLICATE KEY UPDATE `value`='16'"
        ).catch(migCatch);
        logger.info('[schema] v16: Instructor rates + Employee bonuses ready');
      }

      // ── v17: Deduplicate enrollments + add UNIQUE KEY on (subscriber_id, course_id) ──
      if (currentV < 17) {
        // Step 1: Remove duplicate enrollments — keep oldest per (subscriber_id, course_id)
        // Uses self-join DELETE: safe in MySQL, keeps the row with earliest enrolled_at
        // Tie-break on id (lexicographic) so exactly one row survives per pair
        const [dedupResult] = await pool.query(`
          DELETE e1 FROM enrollments e1
          INNER JOIN enrollments e2
            ON e1.subscriber_id = e2.subscriber_id
            AND e1.course_id = e2.course_id
            AND e1.course_id IS NOT NULL
            AND (e1.enrolled_at > e2.enrolled_at
              OR (e1.enrolled_at = e2.enrolled_at AND e1.id > e2.id))
        `).catch(e => { logger.warn('[schema] v17 dedup error:', e.message); return [{ affectedRows: 0 }]; });
        const removed = dedupResult?.affectedRows ?? 0;
        if (removed > 0) logger.info(`[schema] v17: removed ${removed} duplicate enrollment rows`);

        // Step 2: Add UNIQUE KEY — prevents future duplicate enrollments
        // ON DUPLICATE KEY UPDATE in INSERT statements will now work correctly
        await pool.query(
          'ALTER TABLE enrollments ADD UNIQUE KEY uniq_enroll_sub_course (subscriber_id, course_id)'
        ).catch(e => logger.warn('[schema] v17 unique key (may already exist):', e.message));

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '17') ON DUPLICATE KEY UPDATE `value`='17'"
        ).catch(migCatch);
        logger.info('[schema] v17: enrollment dedup + unique constraint ready');
      }

      // ── v18: Backfill leads.status = converted for leads that have a matching subscriber ──
      if (currentV < 18) {
        // Any lead linked via subscribers.lead_id that isn't already converted or lost
        const [leadBackfill] = await pool.query(`
          UPDATE leads l
          INNER JOIN subscribers s ON s.lead_id = l.id
          SET l.status = 'converted'
          WHERE LOWER(l.status) NOT IN ('converted', 'lost')
        `).catch(e => { logger.warn('[schema] v18 lead backfill error:', e.message); return [{ affectedRows: 0 }]; });
        const converted = leadBackfill?.affectedRows ?? 0;
        if (converted > 0) logger.info(`[schema] v18: backfilled ${converted} leads to converted`);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '18') ON DUPLICATE KEY UPDATE `value`='18'"
        ).catch(migCatch);
        logger.info('[schema] v18: leads converted backfill ready');
      }

      // ── v19: Backfill assigned_sales_id/assigned_cs_id from crm_json → DB columns ──
      if (currentV < 19) {
        // Many subscribers have assignedSalesId/assignedCollectionId only in crm_json
        // This migration extracts them into proper DB columns for indexed querying
        const [subs] = await pool.query(
          `SELECT id, crm_json, assigned_sales_id, assigned_cs_id FROM subscribers
           WHERE crm_json IS NOT NULL
             AND (assigned_sales_id IS NULL OR assigned_cs_id IS NULL)
           LIMIT 2000`
        ).catch(() => [[]]);
        let salesFixed = 0, csFixed = 0;
        for (const sub of subs) {
          let crm = {};
          try { crm = JSON.parse(sub.crm_json || '{}'); } catch { continue; }
          const salesId   = crm.assignedSalesId   || null;
          const salesName = crm.assignedSalesName || null;
          const csId      = crm.assignedCollectionId   || crm.assignedCsId   || null;
          const csName    = crm.assignedCollectionName || crm.assignedCsName || null;
          if ((salesId && !sub.assigned_sales_id) || (csId && !sub.assigned_cs_id)) {
            await pool.query(
              `UPDATE subscribers SET
                 assigned_sales_id   = COALESCE(assigned_sales_id, ?),
                 assigned_sales_name = COALESCE(assigned_sales_name, ?),
                 assigned_cs_id      = COALESCE(assigned_cs_id, ?),
                 assigned_cs_name    = COALESCE(assigned_cs_name, ?)
               WHERE id = ?`,
              [salesId, salesName, csId, csName, sub.id]
            ).catch(migCatch);
            if (salesId && !sub.assigned_sales_id) salesFixed++;
            if (csId   && !sub.assigned_cs_id)   csFixed++;
          }
        }
        if (salesFixed > 0 || csFixed > 0)
          logger.info(`[schema] v19: backfilled ${salesFixed} sales assignments + ${csFixed} collection assignments`);

        const [branchBackfill] = await pool.query(
          `UPDATE subscribers
           SET branch = COALESCE(NULLIF(branch, ''), 'ONLINE_EGYPT'),
               branch_id = COALESCE(NULLIF(branch_id, ''), ?)
           WHERE branch IS NULL OR branch='' OR branch_id IS NULL OR branch_id=''`,
          [branchIdForBranch('ONLINE_EGYPT')]
        ).catch(e => { logger.warn('[schema] subscriber branch backfill:', e.message); return [{ affectedRows: 0 }]; });
        if (branchBackfill?.affectedRows > 0) {
          logger.info(`[schema] backfilled ${branchBackfill.affectedRows} subscribers with default branch`);
        }

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '19') ON DUPLICATE KEY UPDATE `value`='19'"
        ).catch(migCatch);
        logger.info('[schema] v19: sales/collection assignment backfill ready');
      }

      // ── v20: Create instructor_fees table ──
      if (currentV < 20) {
        await pool.query(`
          CREATE TABLE IF NOT EXISTS instructor_fees (
            id          VARCHAR(36)   NOT NULL DEFAULT (UUID()),
            staff_id    VARCHAR(36)   NOT NULL,
            course_id   VARCHAR(36)   NULL,
            daqqi_round_id VARCHAR(36) NULL,
            fee_type    ENUM('lecture','training','consultation','fixed') NOT NULL DEFAULT 'lecture',
            hours       DECIMAL(5,2)  NULL,
            rate_per_hour DECIMAL(10,2) NULL,
            fixed_amount  DECIMAL(10,2) NULL,
            total_amount  DECIMAL(10,2) NOT NULL DEFAULT 0,
            currency    ENUM('EGP','SAR','USD') NOT NULL DEFAULT 'EGP',
            period_month TINYINT UNSIGNED NULL,
            period_year  SMALLINT UNSIGNED NULL,
            status      ENUM('pending','approved','paid') NOT NULL DEFAULT 'pending',
            note        TEXT NULL,
            created_by  VARCHAR(36) NULL,
            created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            KEY idx_if_staff    (staff_id),
            KEY idx_if_course   (course_id),
            KEY idx_if_period   (period_year, period_month),
            KEY idx_if_status   (status)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v20 instructor_fees:', e.message));

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '20') ON DUPLICATE KEY UPDATE `value`='20'"
        ).catch(migCatch);
        logger.info('[schema] v20: instructor_fees table ready');
      }

      // ── v21: Add branch_id to payments for per-branch revenue filtering ────────
      if (currentV < 21) {
        await pool.query(`ALTER TABLE payments ADD COLUMN IF NOT EXISTS branch
          ENUM('DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','OTHER') DEFAULT NULL
          AFTER subscriber_id`).catch(e => logger.warn('[schema] v21 payments.branch:', e.message));
        await pool.query('ALTER TABLE payments ADD INDEX IF NOT EXISTS idx_payments_branch (branch)').catch(migCatch);
        // Backfill branch from subscribers table for existing payments
        await pool.query(`
          UPDATE payments p
          JOIN subscribers s ON s.id = p.subscriber_id
          SET p.branch = s.branch
          WHERE p.branch IS NULL AND s.branch IS NOT NULL
        `).catch(e => logger.warn('[schema] v21 payments backfill:', e.message));
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '21') ON DUPLICATE KEY UPDATE `value`='21'"
        ).catch(migCatch);
        logger.info('[schema] v21: payments.branch column + backfill ready');
      }

      // ── Missing composite indexes for hot query paths (always run — idempotent) ─
      await pool.query('ALTER TABLE enrollments ADD INDEX IF NOT EXISTS idx_enroll_sub_course (subscriber_id, course_id)').catch(migCatch);
      await pool.query('ALTER TABLE crm_commissions ADD INDEX IF NOT EXISTS idx_comm_year_month_status (year, month, status)').catch(migCatch);
      await pool.query('ALTER TABLE attendance_logs ADD INDEX IF NOT EXISTS idx_att_staff_date (staff_id, date)').catch(migCatch);
      await pool.query('ALTER TABLE salary_advances ADD INDEX IF NOT EXISTS idx_adv_staff_month (staff_id, deduct_month, deduct_year)').catch(migCatch);
      await pool.query('ALTER TABLE payments ADD INDEX IF NOT EXISTS idx_pay_staff_date (staff_id, date, status)').catch(migCatch);
      await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_leads_assigned_sales (assigned_sales_id)').catch(migCatch);
      await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_leads_assigned_cs (assigned_cs_id)').catch(migCatch);
      await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_leads_hidden (hidden)').catch(migCatch);
      await pool.query('ALTER TABLE subscribers ADD INDEX IF NOT EXISTS idx_subs_sales (assigned_sales_id)').catch(migCatch);
      await pool.query('ALTER TABLE crm_commissions ADD INDEX IF NOT EXISTS idx_comm_client (client_id)').catch(migCatch);
      // Hot-path indexes added in Phase 6 audit
      await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_leads_status (status)').catch(migCatch);
      await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_leads_phone (phone(20))').catch(migCatch);
      await pool.query('ALTER TABLE subscribers ADD INDEX IF NOT EXISTS idx_subs_phone (phone(20))').catch(migCatch);
      await addIndexIfColumnsExist('users', 'idx_users_firebase', 'firebase_uid(191)', ['firebase_uid']);
      await addIndexIfColumnsExist('subscribers', 'idx_subs_status', 'status', ['status']);
      logger.info('[schema] composite indexes ensured');

      // ── v22: Double-entry accounting + instructor revenue share + FK cleanup ──
      if (currentV < 22) {
        // journal_entries — header record (one per payment/refund/payroll event)
        await pool.query(`
          CREATE TABLE IF NOT EXISTS journal_entries (
            id           VARCHAR(36)    NOT NULL DEFAULT (UUID()),
            ref_type     VARCHAR(50)    NOT NULL COMMENT 'payment | refund | payroll | adjustment',
            ref_id       VARCHAR(36)    NULL,
            entry_date   DATE           NOT NULL,
            description  TEXT           NULL,
            total_debit  DECIMAL(12,2)  NOT NULL DEFAULT 0,
            total_credit DECIMAL(12,2)  NOT NULL DEFAULT 0,
            posted_by    VARCHAR(200)   NULL,
            created_at   DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            KEY idx_je_ref  (ref_type, ref_id),
            KEY idx_je_date (entry_date)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v22 journal_entries:', e.message));

        // journal_entry_lines — debit/credit lines for each entry
        await pool.query(`
          CREATE TABLE IF NOT EXISTS journal_entry_lines (
            id           VARCHAR(36)    NOT NULL DEFAULT (UUID()),
            entry_id     VARCHAR(36)    NOT NULL,
            account_code VARCHAR(20)    NOT NULL,
            account_name VARCHAR(200)   NOT NULL,
            debit        DECIMAL(12,2)  NOT NULL DEFAULT 0,
            credit       DECIMAL(12,2)  NOT NULL DEFAULT 0,
            PRIMARY KEY (id),
            KEY idx_jel_entry (entry_id),
            CONSTRAINT fk_jel_entry FOREIGN KEY (entry_id) REFERENCES journal_entries (id) ON DELETE CASCADE
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v22 journal_entry_lines:', e.message));

        // Add revenue_share_pct to instructor_rates (percentage of payment amount)
        await pool.query('ALTER TABLE instructor_rates ADD COLUMN IF NOT EXISTS revenue_share_pct DECIMAL(5,2) DEFAULT 0 COMMENT \'% of course payment auto-credited as instructor fee\'').catch(migCatch);

        // Clean orphan client_id values then add FK
        await pool.query(`
          UPDATE crm_commissions c
          LEFT JOIN subscribers s ON s.id = c.client_id
          SET c.client_id = NULL
          WHERE c.client_id IS NOT NULL AND s.id IS NULL
        `).catch(e => logger.warn('[schema] v22 orphan cleanup:', e.message));
        await pool.query('ALTER TABLE crm_commissions DROP FOREIGN KEY IF EXISTS fk_comm_client').catch(migCatch);
        await pool.query(`
          ALTER TABLE crm_commissions
          ADD CONSTRAINT fk_comm_client FOREIGN KEY (client_id) REFERENCES subscribers(id) ON DELETE SET NULL
        `).catch(e => logger.warn('[schema] v22 FK crm_commissions.client_id:', e.message));

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '22') ON DUPLICATE KEY UPDATE `value`='22'"
        ).catch(migCatch);
        logger.info('[schema] v22: journal tables + instructor revenue_share_pct + crm_commissions FK ready');
      }

      // ── v23: Progress tracking, Drip content, Live sessions, Email sequences ──
      if (currentV < 23) {
        // 1. Lecture completions — student progress tracking
        await pool.query(`
          CREATE TABLE IF NOT EXISTS lecture_completions (
            id            VARCHAR(36) NOT NULL DEFAULT (UUID()),
            subscriber_id VARCHAR(36) NOT NULL,
            lecture_id    VARCHAR(36) NOT NULL,
            course_id     VARCHAR(36) NULL,
            progress_pct  TINYINT UNSIGNED NOT NULL DEFAULT 100,
            completed_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            watch_seconds INT UNSIGNED NOT NULL DEFAULT 0,
            PRIMARY KEY (id),
            UNIQUE KEY uniq_lc (subscriber_id, lecture_id),
            KEY idx_lc_sub  (subscriber_id),
            KEY idx_lc_course (course_id)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v23 lecture_completions:', e.message));

        // 2. Drip unlock: add drip_unlock_days per lecture
        await pool.query('ALTER TABLE lectures ADD COLUMN IF NOT EXISTS drip_unlock_days SMALLINT UNSIGNED DEFAULT 0 COMMENT \'0=instant, N=unlock N days after enrollment\'').catch(migCatch);

        // 3. Live sessions (Zoom / Google Meet per course)
        await pool.query(`
          CREATE TABLE IF NOT EXISTS live_sessions (
            id            VARCHAR(36)  NOT NULL DEFAULT (UUID()),
            course_id     VARCHAR(36)  NULL,
            title         VARCHAR(255) NOT NULL DEFAULT '',
            platform      ENUM('zoom','google_meet','youtube','other') NOT NULL DEFAULT 'zoom',
            meeting_url   TEXT         NOT NULL,
            meeting_id    VARCHAR(200) NULL,
            meeting_pass  VARCHAR(100) NULL,
            starts_at     DATETIME     NOT NULL,
            duration_min  SMALLINT UNSIGNED NOT NULL DEFAULT 60,
            status        ENUM('scheduled','live','ended','cancelled') NOT NULL DEFAULT 'scheduled',
            recording_url TEXT         NULL,
            notes         TEXT         NULL,
            created_by    VARCHAR(200) NULL,
            created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            KEY idx_ls_course (course_id),
            KEY idx_ls_starts (starts_at)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v23 live_sessions:', e.message));

        // 4. Email sequences
        await pool.query(`
          CREATE TABLE IF NOT EXISTS email_sequences (
            id           VARCHAR(36)  NOT NULL DEFAULT (UUID()),
            name         VARCHAR(200) NOT NULL,
            trigger_event ENUM('registration','enrollment','payment','lead_created') NOT NULL DEFAULT 'registration',
            is_active    TINYINT(1)   NOT NULL DEFAULT 1,
            created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v23 email_sequences:', e.message));

        await pool.query(`
          CREATE TABLE IF NOT EXISTS email_sequence_steps (
            id          VARCHAR(36)  NOT NULL DEFAULT (UUID()),
            sequence_id VARCHAR(36)  NOT NULL,
            step_order  TINYINT UNSIGNED NOT NULL DEFAULT 1,
            delay_hours INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'hours after trigger to send',
            subject     VARCHAR(500) NOT NULL DEFAULT '',
            body_html   LONGTEXT     NOT NULL,
            PRIMARY KEY (id),
            KEY idx_ess_seq (sequence_id)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v23 email_sequence_steps:', e.message));

        await pool.query(`
          CREATE TABLE IF NOT EXISTS email_sequence_queue (
            id           VARCHAR(36)  NOT NULL DEFAULT (UUID()),
            step_id      VARCHAR(36)  NOT NULL,
            recipient_email VARCHAR(320) NOT NULL,
            recipient_name  VARCHAR(255) NULL,
            scheduled_at DATETIME     NOT NULL,
            sent_at      DATETIME     NULL,
            failed_at    DATETIME     NULL,
            error_msg    TEXT         NULL,
            PRIMARY KEY (id),
            KEY idx_esq_step      (step_id),
            KEY idx_esq_scheduled (scheduled_at),
            KEY idx_esq_email     (recipient_email)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `).catch(e => logger.warn('[schema] v23 email_sequence_queue:', e.message));

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '23') ON DUPLICATE KEY UPDATE `value`='23'"
        ).catch(migCatch);
        logger.info('[schema] v23: lecture_completions + live_sessions + email_sequences + drip_unlock_days ready');
      }
      // ── v24: courses description + short_description columns ──────────────────
      if (currentV < 24) {
        await pool.query("ALTER TABLE courses ADD COLUMN IF NOT EXISTS description TEXT NULL").catch(migCatch);
        await pool.query("ALTER TABLE courses ADD COLUMN IF NOT EXISTS short_description TEXT NULL").catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '24') ON DUPLICATE KEY UPDATE `value`='24'"
        ).catch(migCatch);
        logger.info('[schema] v24: courses description + short_description ready');
      }
      // ── v25: course_lectures description + is_preview + is_published columns ─
      if (currentV < 25) {
        await pool.query("ALTER TABLE course_lectures ADD COLUMN IF NOT EXISTS description TEXT NULL").catch(migCatch);
        await pool.query("ALTER TABLE course_lectures ADD COLUMN IF NOT EXISTS is_preview TINYINT(1) NOT NULL DEFAULT 0").catch(migCatch);
        await pool.query("ALTER TABLE course_lectures ADD COLUMN IF NOT EXISTS is_published TINYINT(1) NOT NULL DEFAULT 1").catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '25') ON DUPLICATE KEY UPDATE `value`='25'"
        ).catch(migCatch);
        logger.info('[schema] v25: course_lectures description + is_preview + is_published ready');
      }
      // ── v26: course_lectures drip_unlock_days column ──────────────────────────
      if (currentV < 26) {
        await pool.query("ALTER TABLE course_lectures ADD COLUMN IF NOT EXISTS drip_unlock_days INT NOT NULL DEFAULT 0").catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '26') ON DUPLICATE KEY UPDATE `value`='26'"
        ).catch(migCatch);
        logger.info('[schema] v26: course_lectures drip_unlock_days ready');
      }
      // ── v27: DB-level unique constraints to prevent duplicate clients ─────────
      if (currentV < 27) {
        // 1. Normalize empty phones to NULL (can't have UNIQUE on empty strings)
        await pool.query(`UPDATE subscribers SET phone = NULL WHERE phone IS NOT NULL AND TRIM(phone) = ''`).catch(migCatch);
        await pool.query(`UPDATE leads SET phone = NULL WHERE phone IS NOT NULL AND TRIM(phone) = ''`).catch(migCatch);

        // 2. Merge duplicate subscribers by phone (keep the one with most data)
        const [subPhoneDups] = await pool.query(
          `SELECT phone, GROUP_CONCAT(id ORDER BY
             (SELECT COUNT(*) FROM enrollments e WHERE e.subscriber_id=s.id) DESC,
             (SELECT COUNT(*) FROM payments p WHERE p.subscriber_id=s.id) DESC,
             created_at ASC
             SEPARATOR ',') AS ids
           FROM subscribers s
           WHERE phone IS NOT NULL AND phone != ''
           GROUP BY phone HAVING COUNT(*) > 1`
        ).catch(() => [[]]);
        for (const row of subPhoneDups || []) {
          const ids = row.ids.split(',');
          const keepId = ids[0];
          for (const rid of ids.slice(1)) {
            await pool.query(`UPDATE enrollments SET subscriber_id=? WHERE subscriber_id=? AND subscriber_id NOT IN (SELECT subscriber_id FROM enrollments WHERE subscriber_id=?)`, [keepId, rid, keepId]).catch(migCatch);
            await pool.query(`UPDATE payments SET subscriber_id=? WHERE subscriber_id=?`, [keepId, rid]).catch(migCatch);
            await pool.query(`DELETE FROM subscribers WHERE id=?`, [rid]).catch(migCatch);
          }
        }

        // 3. Merge duplicate subscribers by email (keep best)
        const [subEmailDups] = await pool.query(
          `SELECT LOWER(TRIM(email)) AS em,
             GROUP_CONCAT(id ORDER BY
               (CASE WHEN client_code REGEXP '^C[0-9]+$' THEN 0 ELSE 1 END),
               created_at ASC SEPARATOR ',') AS ids
           FROM subscribers
           WHERE email IS NOT NULL AND email != ''
           GROUP BY LOWER(TRIM(email)) HAVING COUNT(*) > 1`
        ).catch(() => [[]]);
        for (const row of subEmailDups || []) {
          const ids = row.ids.split(',');
          const keepId = ids[0];
          for (const rid of ids.slice(1)) {
            await pool.query(`UPDATE enrollments SET subscriber_id=? WHERE subscriber_id=?`, [keepId, rid]).catch(migCatch);
            await pool.query(`UPDATE payments SET subscriber_id=? WHERE subscriber_id=?`, [keepId, rid]).catch(migCatch);
            await pool.query(`DELETE FROM subscribers WHERE id=?`, [rid]).catch(migCatch);
          }
        }

        // 4. Merge duplicate leads by phone (keep newest, hide older)
        const [leadPhoneDups] = await pool.query(
          `SELECT phone, GROUP_CONCAT(id ORDER BY created_at DESC SEPARATOR ',') AS ids
           FROM leads
           WHERE phone IS NOT NULL AND phone != '' AND hidden=0
           GROUP BY phone HAVING COUNT(*) > 1`
        ).catch(() => [[]]);
        for (const row of leadPhoneDups || []) {
          const ids = row.ids.split(',');
          const keepId = ids[0];
          for (const rid of ids.slice(1)) {
            await pool.query(`UPDATE leads SET hidden=1 WHERE id=?`, [rid]).catch(migCatch);
          }
        }

        // 5. Merge duplicate leads by email (hide older)
        const [leadEmailDups] = await pool.query(
          `SELECT LOWER(TRIM(email)) AS em,
             GROUP_CONCAT(id ORDER BY created_at DESC SEPARATOR ',') AS ids
           FROM leads
           WHERE email IS NOT NULL AND email != '' AND hidden=0
           GROUP BY LOWER(TRIM(email)) HAVING COUNT(*) > 1`
        ).catch(() => [[]]);
        for (const row of leadEmailDups || []) {
          const ids = row.ids.split(',');
          for (const rid of ids.slice(1)) {
            await pool.query(`UPDATE leads SET hidden=1 WHERE id=?`, [rid]).catch(migCatch);
          }
        }

        // 6. Now add UNIQUE constraints (safe — duplicates are gone)
        await pool.query(`ALTER TABLE subscribers ADD CONSTRAINT uq_subs_phone UNIQUE (phone(50))`).catch(migCatch);
        await pool.query(`ALTER TABLE subscribers ADD CONSTRAINT uq_subs_email UNIQUE (email(191))`).catch(migCatch);
        await pool.query(`ALTER TABLE subscribers ADD CONSTRAINT uq_subs_code  UNIQUE (client_code(50))`).catch(migCatch);
        // Note: leads uses hidden=1 instead of DELETE so we can't add a UNIQUE — app-level checks are the guard

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '27') ON DUPLICATE KEY UPDATE `value`='27'"
        ).catch(migCatch);
        logger.info('[schema] v27: duplicate client cleanup + phone/email/code UNIQUE constraints on subscribers ready');
      }

      // ── v28: Add missing salary_structures columns for payroll calculation ──
      if (currentV < 28) {
        await pool.query('ALTER TABLE salary_structures ADD COLUMN IF NOT EXISTS food_allowance DECIMAL(10,2) NOT NULL DEFAULT 0').catch(migCatch);
        await pool.query('ALTER TABLE salary_structures ADD COLUMN IF NOT EXISTS other_fixed DECIMAL(10,2) NOT NULL DEFAULT 0').catch(migCatch);
        await pool.query('ALTER TABLE salary_structures ADD COLUMN IF NOT EXISTS deduction_social_insurance DECIMAL(10,2) NOT NULL DEFAULT 0').catch(migCatch);
        await pool.query('ALTER TABLE salary_structures ADD COLUMN IF NOT EXISTS deduction_tax DECIMAL(10,2) NOT NULL DEFAULT 0').catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '28') ON DUPLICATE KEY UPDATE `value`='28'"
        ).catch(migCatch);
        logger.info('[schema] v28: salary_structures food/social/tax columns added');
      }

      // ── v29: Delete ghost subscribers created by the login auto-create bug ──
      // These are subscribers with no enrollments + no payments + no valid client_code
      // who were auto-inserted when any user logged in (even without purchasing).
      if (currentV < 29) {
        try {
          const [ghosts] = await pool.query(
            `SELECT s.id FROM subscribers s
             LEFT JOIN enrollments e ON e.subscriber_id = s.id
             LEFT JOIN payments p ON p.subscriber_id = s.id
             WHERE e.id IS NULL AND p.id IS NULL
               AND (s.client_code IS NULL OR s.client_code NOT REGEXP '^C[0-9]+$')`
          );
          if (ghosts.length > 0) {
            const ids = ghosts.map(r => r.id);
            for (let i = 0; i < ids.length; i += 500) {
              const batch = ids.slice(i, i + 500);
              await pool.query(`DELETE FROM subscribers WHERE id IN (${batch.map(() => '?').join(',')})`, batch).catch(migCatch);
            }
            logger.info(`[schema] v29: deleted ${ghosts.length} ghost subscriber(s) (no enrollments, no payments, no code)`);
          }
        } catch (ge) { logger.warn('[schema] v29 ghost cleanup error (non-fatal):', ge.message); }
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '29') ON DUPLICATE KEY UPDATE `value`='29'"
        ).catch(migCatch);
        logger.info('[schema] v29: ghost subscriber cleanup done');
      }

      // ── v30: Make subscribers.email nullable so clients without email don't ──
      // conflict on the UNIQUE KEY. Multiple NULL values are allowed by MySQL's
      // UNIQUE constraint, unlike duplicate empty strings which are rejected.
      if (currentV < 30) {
        await pool.query(
          "ALTER TABLE subscribers MODIFY COLUMN email VARCHAR(255) NULL DEFAULT NULL"
        ).catch(migCatch);
        // Convert existing empty-string emails to NULL
        await pool.query(
          "UPDATE subscribers SET email = NULL WHERE email = ''"
        ).catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '30') ON DUPLICATE KEY UPDATE `value`='30'"
        ).catch(migCatch);
        logger.info('[schema] v30: subscribers.email made nullable');
      }

      // ── v31: Create daqqi tables if not exists + fix instructor FK ────────────
      if (currentV < 31) {
        // Ensure daqqi_rounds table exists (without the wrong instructor→staff FK)
        await pool.query(`
          CREATE TABLE IF NOT EXISTS daqqi_rounds (
            id                   VARCHAR(36)  NOT NULL DEFAULT (UUID()),
            code                 VARCHAR(50)  NOT NULL,
            course_id            VARCHAR(36)  NOT NULL,
            instructor_id        VARCHAR(36)  NOT NULL,
            instructor_name      VARCHAR(255) NOT NULL,
            reception_id         VARCHAR(36)  NOT NULL,
            reception_name       VARCHAR(255) NOT NULL,
            day_of_week          VARCHAR(20)  NOT NULL,
            start_date           DATETIME NOT NULL,
            time_slot            ENUM('MORNING','NOON','EVENING') NOT NULL,
            status               ENUM('NEW','ACTIVE','FINISHED') NOT NULL DEFAULT 'NEW',
            current_lecture      INT NOT NULL DEFAULT 0,
            postponed_weeks_json TEXT DEFAULT NULL,
            created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id),
            UNIQUE KEY idx_daqqi_code (code)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        `).catch(e => logger.warn('[schema] v31 daqqi_rounds:', e.message));

        // Ensure daqqi_attendees table exists
        await pool.query(`
          CREATE TABLE IF NOT EXISTS daqqi_attendees (
            round_id          VARCHAR(36)  NOT NULL,
            subscriber_id     VARCHAR(36)  NOT NULL,
            name              VARCHAR(255) NOT NULL,
            phone             VARCHAR(50)  NOT NULL,
            booked_at         DATETIME NOT NULL,
            amount_paid       DOUBLE NOT NULL DEFAULT 0,
            attended_lectures INT NOT NULL DEFAULT 0,
            PRIMARY KEY (round_id, subscriber_id),
            KEY idx_att_subscriber (subscriber_id)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        `).catch(e => logger.warn('[schema] v31 daqqi_attendees:', e.message));

        // Drop the wrong FK that points instructor_id → staff(id).
        // Instructors come from the therapists table, not staff.
        await pool.query('ALTER TABLE daqqi_rounds DROP FOREIGN KEY fk_daqqi_instructor').catch(migCatch);

        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '31') ON DUPLICATE KEY UPDATE `value`='31'"
        ).catch(migCatch);
        logger.info('[schema] v31: daqqi tables ensured + instructor FK fixed');
      }

      if (currentV < 32) {
        // Performance indexes
        await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_source (source)').catch(migCatch);
        await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_status_created (status, created_at)').catch(migCatch);
        await pool.query('ALTER TABLE subscribers ADD INDEX IF NOT EXISTS idx_branch (branch)').catch(migCatch);
        await pool.query('ALTER TABLE payments ADD INDEX IF NOT EXISTS idx_status_branch (status, branch)').catch(migCatch);
        // Tickets SLA + escalation columns
        await pool.query("ALTER TABLE tickets ADD COLUMN IF NOT EXISTS priority ENUM('low','medium','high','urgent') DEFAULT 'medium'").catch(migCatch);
        await pool.query('ALTER TABLE tickets ADD COLUMN IF NOT EXISTS sla_hours INT DEFAULT 24').catch(migCatch);
        await pool.query('ALTER TABLE tickets ADD COLUMN IF NOT EXISTS responded_at DATETIME NULL').catch(migCatch);
        await pool.query('ALTER TABLE tickets ADD COLUMN IF NOT EXISTS resolved_at DATETIME NULL').catch(migCatch);
        await pool.query('ALTER TABLE tickets ADD COLUMN IF NOT EXISTS sla_breached TINYINT(1) DEFAULT 0').catch(migCatch);
        await pool.query('ALTER TABLE tickets ADD COLUMN IF NOT EXISTS escalated_to INT NULL').catch(migCatch);
        await pool.query('ALTER TABLE tickets ADD COLUMN IF NOT EXISTS escalated_at DATETIME NULL').catch(migCatch);
        await pool.query(`CREATE TABLE IF NOT EXISTS canned_responses (
          id INT AUTO_INCREMENT PRIMARY KEY,
          title VARCHAR(200) NOT NULL,
          body TEXT NOT NULL,
          category VARCHAR(100),
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '32') ON DUPLICATE KEY UPDATE `value`='32'"
        ).catch(migCatch);
        logger.info('[schema] v32: performance indexes + tickets SLA + canned_responses');
      }

      if (currentV < 33) {
        // Waitlist for branches (initially Daqqi)
        await pool.query(`
          CREATE TABLE IF NOT EXISTS daqqi_waitlist (
            id VARCHAR(36) PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            phone VARCHAR(50) NOT NULL,
            email VARCHAR(255),
            course_id VARCHAR(36),
            course_name VARCHAR(255),
            notes TEXT,
            status ENUM('waiting','contacted','enrolled','cancelled') DEFAULT 'waiting',
            branch ENUM('DAQQI','TAGAMOA','ONLINE_EGYPT','ONLINE_SAUDI','ONLINE_ABROAD','OTHER') DEFAULT 'DAQQI',
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        // Accounting periods for period-closing
        await pool.query(`
          CREATE TABLE IF NOT EXISTS accounting_periods (
            id VARCHAR(36) PRIMARY KEY,
            period_label VARCHAR(20) NOT NULL,
            opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            closed_at DATETIME NULL,
            closed_by VARCHAR(100) NULL,
            summary_json TEXT NULL,
            status ENUM('open','closed') DEFAULT 'open'
          ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`).catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '33') ON DUPLICATE KEY UPDATE `value`='33'"
        ).catch(migCatch);
        logger.info('[schema] v33: daqqi_waitlist + accounting_periods');
      }
      if (currentV < 41) {
        await pool.query('ALTER TABLE leads ADD COLUMN IF NOT EXISTS retargeting_sent_at DATETIME NULL').catch(migCatch);
        await pool.query('ALTER TABLE leads ADD INDEX IF NOT EXISTS idx_leads_retargeting_sent_at (retargeting_sent_at)').catch(migCatch);
        await pool.query(
          "INSERT INTO site_config (`key`, `value`) VALUES ('schema_version', '41') ON DUPLICATE KEY UPDATE `value`='41'"
        ).catch(migCatch);
        logger.info('[schema] v41: lead retargeting timestamp ready');
      }
    } catch (e) { logger.warn('[schema] migration error (non-fatal):', e.message); }
  })();

  // ── STARTUP: Restore institute.branches + add client_type column ─────────────
  // Reverts erroneous branch taxonomy migration; restores original branches.
  // Also adds client_type VARCHAR column to subscribers and leads if missing.
  setTimeout(async () => {
    try {
      // 1. Restore original institute.branches in content (undo previous mistake)
      const ORIGINAL_BRANCHES = [
        { id: 'DAQQI',         label: 'الدقي'         },
        { id: 'TAGAMOA',       label: 'التجمع'        },
        { id: 'ONLINE_EGYPT',  label: 'أونلاين مصر'   },
        { id: 'ONLINE_SAUDI',  label: 'أونلاين السعودية' },
        { id: 'ONLINE_ABROAD', label: 'أونلاين الخارج'  },
        { id: 'OTHER',         label: 'أخرى'           },
      ];
      const [[row]] = await pool.query("SELECT `value` FROM site_config WHERE `key`='content' LIMIT 1");
      const content = row ? JSON.parse(row.value || '{}') : {};
      const existingBranches = (() => { try { return JSON.parse(content['institute.branches'] || '[]'); } catch { return []; } })();
      // Revert if it was wrongly set to the type taxonomy (check for ONLINE_LOCAL_NEW)
      const wasWronglyMigrated = Array.isArray(existingBranches) && existingBranches.some(b => b.id === 'ONLINE_LOCAL_NEW');
      if (wasWronglyMigrated) {
        content['institute.branches'] = JSON.stringify(ORIGINAL_BRANCHES);
        await pool.query(
          "INSERT INTO site_config (`key`,`value`) VALUES ('content',?) ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)",
          [JSON.stringify(content)]
        );
        logger.info('[Startup] institute.branches restored to original branch taxonomy');
      }
    } catch (e) { logger.warn('[Startup] branch restore error (non-fatal):', e.message); }

    try {
      // 2. Add client_type VARCHAR column to subscribers if missing
      await pool.query(`ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS client_type VARCHAR(50) DEFAULT NULL`);
      // 3. Add client_type VARCHAR column to leads if missing
      await pool.query(`ALTER TABLE leads ADD COLUMN IF NOT EXISTS client_type VARCHAR(50) DEFAULT NULL`);
      logger.info('[Startup] client_type columns ensured on subscribers + leads');
    } catch (e) { logger.warn('[Startup] client_type column migration error (non-fatal):', e.message); }
  }, 8_000);

  // ── STARTUP: Auto-sync paymentHistory → payments table ───────────────────────
  // Delayed 45s after startup so the server starts listening immediately.
  // INSERT IGNORE = safe to repeat. Runs in cursor-based batches to handle 5000+ subscribers.
  setTimeout(async () => {
    try {
      let lastId = '';
      let totalInserted = 0;
      while (true) {
        const [rows] = await pool.query(
          `SELECT id, crm_json FROM subscribers WHERE crm_json IS NOT NULL
           AND JSON_LENGTH(JSON_EXTRACT(crm_json, '$.paymentHistory')) > 0
           AND id > ? ORDER BY id ASC LIMIT 1000`,
          [lastId]
        );
        if (rows.length === 0) break;
      const courseIds = new Set();
      const bundleIds = new Set();
      for (const row of rows) {
        const crm = tryJson(row.crm_json, {});
        const history = Array.isArray(crm.paymentHistory) ? crm.paymentHistory : [];
        for (const p of history) {
          if (p.courseId) courseIds.add(String(p.courseId));
          if (p.bundleId) bundleIds.add(String(p.bundleId));
        }
      }
      const existingCourseIds = new Set();
      const existingBundleIds = new Set();
      if (courseIds.size) {
        const ids = Array.from(courseIds);
        const [existing] = await pool.query(
          `SELECT id FROM courses WHERE id IN (${ids.map(() => '?').join(',')})`,
          ids
        );
        existing.forEach((r) => existingCourseIds.add(String(r.id)));
      }
      if (bundleIds.size) {
        const ids = Array.from(bundleIds);
        const [existing] = await pool.query(
          `SELECT id FROM bundles WHERE id IN (${ids.map(() => '?').join(',')})`,
          ids
        );
        existing.forEach((r) => existingBundleIds.add(String(r.id)));
      }
      const valueTuples = [];
      const params = [];
      for (const row of rows) {
        const crm = tryJson(row.crm_json, {});
        const history = Array.isArray(crm.paymentHistory) ? crm.paymentHistory : [];
        for (const p of history) {
          if (!p.id || !p.amount || Number(p.amount) <= 0) continue;
          const pType = (p.paymentType || 'OTHER').toUpperCase();
          const safePayType = VALID_PAY_TYPES.has(pType) ? pType : 'OTHER';
          const dateVal = (p.at || p.date || new Date().toISOString()).slice(0, 10);
          const payStatus = p.status || 'paid';
          const safeSource = VALID_SOURCES.has(p.source) ? p.source : null;
          const courseId = p.courseId && existingCourseIds.has(String(p.courseId)) ? p.courseId : null;
          const bundleId = p.bundleId && existingBundleIds.has(String(p.bundleId)) ? p.bundleId : null;
          valueTuples.push('(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
          params.push(
            p.id, row.id, courseId, bundleId, Number(p.amount)||0,
            p.currency||'EGP', safePayType, p.paymentMethod||null, p.transactionId||null,
            p.isInstallment?1:0,
            p.courseExpected != null ? Number(p.courseExpected) : null,
            dateVal, p.note||null, payStatus, p.staffId||null,
            p.staffName||null, p.fromAccountNumber||null, safeSource, p.itemTitle||null, p.certType||null
          );
        }
      }
      if (valueTuples.length > 0) {
        const [r] = await pool.query(
          `INSERT INTO payments
             (id, subscriber_id, course_id, bundle_id, amount, currency, payment_type,
              payment_method, transaction_id, is_installment, course_expected, date, note, status, staff_id,
              staff_name, from_account, source, item_title, cert_type)
           VALUES ${valueTuples.join(',')}
           ON DUPLICATE KEY UPDATE status=VALUES(status), note=COALESCE(VALUES(note),note),
             staff_name=COALESCE(VALUES(staff_name),staff_name),
             from_account=COALESCE(VALUES(from_account),from_account),
             source=COALESCE(VALUES(source),source),
             item_title=COALESCE(VALUES(item_title),item_title),
             cert_type=COALESCE(VALUES(cert_type),cert_type),
             course_expected=COALESCE(course_expected,VALUES(course_expected))`,
          params
        ).catch(e => { logger.warn('[Startup] payments sync bulk insert error:', e.message); return [{ affectedRows: 0 }]; });
        totalInserted += r.affectedRows || 0;
      }
        lastId = rows[rows.length - 1].id;
      }
      if (totalInserted > 0) logger.info(`[Startup] payments sync: inserted/updated ${totalInserted} payment records`);
    } catch (e) { logger.warn('[Startup] payments sync error (non-fatal):', e.message); }
  }, 45_000); // defer 45s so app.listen runs first

  // ── STARTUP: Auto-assign missing client codes (runs on every server start) ────
  // This is the safety net: any lead or subscriber that ended up without a valid
  // Cxxxxx code will be assigned one atomically from the counter.
  // Also detects duplicate leads by phone (keeps newest, hides older ones).
  (async () => {
    try {
      const conn = await pool.getConnection();
      try {
        // 1. Sync counter to be ahead of all existing Cxxxxx codes
        const [[subMax]]  = await conn.query(`SELECT MAX(CAST(SUBSTRING(client_code,2) AS UNSIGNED)) AS mx FROM subscribers WHERE client_code REGEXP '^C[0-9]+$'`);
        const [[leadMax]] = await conn.query(`SELECT MAX(CAST(SUBSTRING(client_code,2) AS UNSIGNED)) AS mx FROM leads WHERE client_code REGEXP '^C[0-9]+$'`);
        const maxExisting = Math.max(subMax.mx || 0, leadMax.mx || 0);
        const safeStart   = maxExisting >= 10000 ? maxExisting + 1 : 10001;
        await conn.query('UPDATE client_code_counter SET next_value = ? WHERE id = 1 AND next_value < ?', [safeStart, safeStart]);

        // 2. Assign codes to leads missing valid codes
        const [leadsNeedCode] = await conn.query(
          `SELECT id FROM leads WHERE client_code IS NULL OR client_code NOT REGEXP '^C[0-9]+$' ORDER BY created_at ASC`
        );
        for (const row of leadsNeedCode) {
          await conn.query('UPDATE client_code_counter SET next_value = next_value + 1 WHERE id = 1');
          const [[cRow]] = await conn.query('SELECT next_value FROM client_code_counter WHERE id = 1');
          const code = `C${cRow.next_value - 1}`;
          await conn.query('UPDATE leads SET client_code = ? WHERE id = ? AND (client_code IS NULL OR client_code NOT REGEXP ?)', [code, row.id, '^C[0-9]+$']);
        }

        // 3. Assign codes to subscribers missing valid codes
        const [subsNeedCode] = await conn.query(
          `SELECT id FROM subscribers WHERE client_code IS NULL OR client_code NOT REGEXP '^C[0-9]+$' ORDER BY created_at ASC`
        );
        for (const row of subsNeedCode) {
          await conn.query('UPDATE client_code_counter SET next_value = next_value + 1 WHERE id = 1');
          const [[cRow]] = await conn.query('SELECT next_value FROM client_code_counter WHERE id = 1');
          const code = `C${cRow.next_value - 1}`;
          await conn.query('UPDATE subscribers SET client_code = ? WHERE id = ? AND (client_code IS NULL OR client_code NOT REGEXP ?)', [code, row.id, '^C[0-9]+$']);
        }

        // 4. Fix duplicate codes: if two records share the same code, re-assign the duplicate
        const [dupCodes] = await conn.query(
          `SELECT client_code, COUNT(*) AS cnt FROM (
             SELECT client_code FROM leads WHERE client_code REGEXP '^C[0-9]+$'
             UNION ALL
             SELECT client_code FROM subscribers WHERE client_code REGEXP '^C[0-9]+$'
           ) t GROUP BY client_code HAVING cnt > 1`
        );
        for (const dup of dupCodes) {
          // Find the lead row(s) with this code (exclude first one by created_at)
          const [ldups] = await conn.query(
            `SELECT id FROM leads WHERE client_code = ? ORDER BY created_at ASC LIMIT 99 OFFSET 1`, [dup.client_code]
          );
          for (const row of ldups) {
            await conn.query('UPDATE client_code_counter SET next_value = next_value + 1 WHERE id = 1');
            const [[cRow]] = await conn.query('SELECT next_value FROM client_code_counter WHERE id = 1');
            await conn.query('UPDATE leads SET client_code = ? WHERE id = ?', [`C${cRow.next_value - 1}`, row.id]);
          }
          // Find subscriber row(s) with this code
          const [sdups] = await conn.query(
            `SELECT id FROM subscribers WHERE client_code = ? ORDER BY created_at ASC LIMIT 99 OFFSET 0`, [dup.client_code]
          );
          // If any subscriber shares a code with a lead, re-assign the subscriber
          for (const row of sdups) {
            const [[leadWithCode]] = await conn.query('SELECT id FROM leads WHERE client_code = ?', [dup.client_code]);
            if (leadWithCode) {
              await conn.query('UPDATE client_code_counter SET next_value = next_value + 1 WHERE id = 1');
              const [[cRow]] = await conn.query('SELECT next_value FROM client_code_counter WHERE id = 1');
              await conn.query('UPDATE subscribers SET client_code = ? WHERE id = ?', [`C${cRow.next_value - 1}`, row.id]);
            }
          }
        }

        const totalFixed = leadsNeedCode.length + subsNeedCode.length;
        if (totalFixed > 0 || dupCodes.length > 0) {
          logger.info(`[Startup] Client codes: assigned ${totalFixed} missing, fixed ${dupCodes.length} duplicate code(s)`);
        }
      } finally { conn.release(); }
    } catch (e) { logger.warn('[Startup] Client code backfill error (non-fatal):', e.message); }
  })();

  // Keep pool connections warm: ping every 4 minutes so MySQL wait_timeout never triggers
  setInterval(async () => {
    try { await pool.query('SELECT 1'); }
    catch (e) { logger.warn('[DB keepalive] ping failed:', e.message); }
  }, 4 * 60 * 1000);

  // ── Scheduled Weekly Payment Reminder ────────────────────────────────────────
  // Every Sunday at 10:00 Cairo time (UTC+2 = 08:00 UTC): send WA reminders to
  // all subscribers with outstanding balances (course_expected > paid).
  // Fires every hour and checks if it is the right day+hour to run once per week.
  let _lastPaymentReminderWeek = -1;
  const LEGACY_STARTUP_REMINDERS_ENABLED = false;
  if (LEGACY_STARTUP_REMINDERS_ENABLED) setInterval(async () => {
    try {
      const now = new Date();
      const cairoHour = (now.getUTCHours() + 2) % 24;
      const weekNum = Math.floor(now.getTime() / (7 * 24 * 60 * 60 * 1000));
      // Sunday = 0, run at 10:00 Cairo (08:00 UTC)
      if (now.getUTCDay() !== 0 || cairoHour !== 8 || weekNum === _lastPaymentReminderWeek) return;
      _lastPaymentReminderWeek = weekNum;
      const [subs] = await pool.query(`
        SELECT s.id, s.name, s.phone,
               COALESCE(SUM(p.course_expected),0) - COALESCE(SUM(p.amount),0) AS outstanding
        FROM subscribers s
        JOIN payments p ON p.subscriber_id = s.id
        WHERE p.course_expected IS NOT NULL AND p.course_expected > 0
        GROUP BY s.id HAVING outstanding > 0 LIMIT 200
      `);
      if (!subs.length) return;
      let sent = 0;
      for (const sub of subs) {
        const ph = (sub.phone || '').replace(/\D/g, '');
        if (!ph) continue;
        const msg = `أهلاً ${sub.name || ''} 💚\nتذكير أسبوعي: لديك رصيد مستحق بمبلغ ${Math.round(sub.outstanding)} ج.م.\nيرجى التواصل معنا لتسوية الرصيد. شكراً 🌿`;
        try { await sendWhatsApp(ph, msg); sent++; } catch (_) {}
      }
      logger.info(`[WeeklyReminder] Sent ${sent}/${subs.length} payment reminders`);
      await pool.query(
        'INSERT INTO activity_logs (id, action, entity, entity_id, label, actor) VALUES (?,?,?,?,?,?)',
        [uuidv4(), 'auto_reminder', 'payments', null, `تذكير أسبوعي تلقائي — ${sent} رسالة`, 'system']
      );
    } catch (e) { logger.warn('[WeeklyReminder] error:', e.message); }
  }, 60 * 60 * 1000); // check every hour

  // ── Self-healing: write watchdog + install cron on every startup ─────────────
  // Hostinger clears crontabs and may delete files periodically.
  // So we re-create watchdog.sh and re-install the cron on EVERY server boot.
}

module.exports = { registerStartupTasks };
