ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS previous_hash CHAR(64) DEFAULT NULL AFTER user_agent,
  ADD COLUMN IF NOT EXISTS event_hash CHAR(64) DEFAULT NULL AFTER previous_hash,
  ADD COLUMN IF NOT EXISTS hash_version TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER event_hash,
  ADD UNIQUE INDEX IF NOT EXISTS uq_audit_logs_tenant_hash (tenant_id, event_hash);

CREATE TABLE IF NOT EXISTS audit_chain_heads (
  tenant_id VARCHAR(64) NOT NULL PRIMARY KEY,
  last_hash CHAR(64) NOT NULL,
  event_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs_archive LIKE audit_logs;

ALTER TABLE audit_logs_archive
  ADD COLUMN IF NOT EXISTS previous_hash CHAR(64) DEFAULT NULL AFTER user_agent,
  ADD COLUMN IF NOT EXISTS event_hash CHAR(64) DEFAULT NULL AFTER previous_hash,
  ADD COLUMN IF NOT EXISTS hash_version TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER event_hash;
