ALTER TABLE staff
  ADD COLUMN IF NOT EXISTS national_id VARCHAR(50) NULL AFTER bank_name,
  ADD COLUMN IF NOT EXISTS address VARCHAR(500) NULL AFTER national_id,
  ADD COLUMN IF NOT EXISTS hr_notes TEXT NULL AFTER address;
