CREATE TABLE cash_flow_forecast_assumptions (
  id VARCHAR(36) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  branch_id VARCHAR(36) NULL,
  direction ENUM('inflow','outflow') NOT NULL,
  category VARCHAR(80) NOT NULL,
  label VARCHAR(255) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  currency ENUM('EGP','SAR','USD') NOT NULL,
  amount_egp DECIMAL(18,2) NOT NULL,
  fx_rate_to_egp DECIMAL(18,8) NOT NULL,
  cadence ENUM('one_time','weekly','monthly') NOT NULL DEFAULT 'one_time',
  start_date DATE NOT NULL,
  end_date DATE NULL,
  confidence_pct DECIMAL(5,2) NOT NULL DEFAULT 100,
  notes VARCHAR(1000) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cash_forecast_window (tenant_id,is_active,start_date,end_date),
  KEY idx_cash_forecast_branch (tenant_id,branch_id,start_date),
  CONSTRAINT chk_cash_forecast_amount CHECK (amount>0 AND amount_egp>0 AND fx_rate_to_egp>0),
  CONSTRAINT chk_cash_forecast_confidence CHECK (confidence_pct>=0 AND confidence_pct<=100),
  CONSTRAINT chk_cash_forecast_dates CHECK (end_date IS NULL OR end_date>=start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
